//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpServerEngineSampleClient.Properties {
    using System;
    
    
    
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EpServerEngineSampleClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        
        internal static System.Drawing.Bitmap ADD_USER {
            get {
                object obj = ResourceManager.GetObject("ADD_USER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        
        internal static System.Drawing.Bitmap DEV_INFO {
            get {
                object obj = ResourceManager.GetObject("DEV_INFO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        
        internal static System.Drawing.Bitmap ID_AND_PWD_SEARCH {
            get {
                object obj = ResourceManager.GetObject("ID_AND_PWD_SEARCH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        
        internal static System.Drawing.Bitmap ID_BOX {
            get {
                object obj = ResourceManager.GetObject("ID_BOX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        
        internal static System.Drawing.Bitmap LOG_IN {
            get {
                object obj = ResourceManager.GetObject("LOG_IN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        
        internal static System.Drawing.Bitmap SignUp_Board {
            get {
                object obj = ResourceManager.GetObject("SignUp_Board", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        
        internal static System.Drawing.Bitmap SIGNUP_CANCEL {
            get {
                object obj = ResourceManager.GetObject("SIGNUP_CANCEL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        
        internal static System.Drawing.Bitmap SIGNUP_OK {
            get {
                object obj = ResourceManager.GetObject("SIGNUP_OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
